from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import landscape, A4
from io import BytesIO
from datetime import datetime

def create_medical_report(user, report):
    buffer = BytesIO()
    
    # 1. Force Landscape A4 Format
    p = canvas.Canvas(buffer, pagesize=landscape(A4))
    width, height = landscape(A4) # width=842, height=595
    
    # Header Section
    p.setFont("Helvetica-Bold", 20)
    p.setFillColorRGB(0, 0.68, 0.93) # #00aeef Light Blue matching your UI
    p.drawString(100, height - 80, "MEDVERIFY DIAGNOSTIC REPORT")
    
    # Line separator
    p.setStrokeColorRGB(0, 0.68, 0.93)
    p.line(100, height - 90, width - 100, height - 90)
    
    # Patient Information
    p.setFillColorRGB(0.17, 0.21, 0.28) # #2d3748 Dark slate
    p.setFont("Helvetica-Bold", 14)
    p.drawString(100, height - 130, "Patient Information")
    
    p.setFont("Helvetica", 12)
    p.drawString(100, height - 150, f"Requested By: {user.get('name', 'N/A')}")
    p.drawString(100, height - 165, f"Patient Age: {user.get('age', 'N/A')}")
    p.drawString(100, height - 180, f"Date of Analysis: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # Dual-Authentication Results
    p.setFont("Helvetica-Bold", 14)
    p.drawString(100, height - 230, "Dual-Verification Results")
    
    p.setFont("Helvetica", 12)
    # AI Verdict
    p.drawString(100, height - 250, f"AI Neural Verdict: {report.get('verdict', 'PENDING')}")
    p.drawString(100, height - 265, f"Detected Batch No: {report.get('batch', 'NOT FOUND')}")
    
    # --- NEW: Cloud Database Logic ---
    p.setFont("Helvetica-Bold", 12)
    p.drawString(100, height - 290, "Cloud Registry Status:")
    p.setFont("Helvetica", 12)
    
    # Change text color based on verdict
    if report.get('verdict') == 'AUTHENTIC':
        p.setFillColorRGB(0, 0.69, 0.45) # Green
    elif report.get('verdict') == 'RECALLED' or report.get('verdict') == 'COUNTERFEIT':
        p.setFillColorRGB(0.88, 0.21, 0.27) # Red
    else:
        p.setFillColorRGB(0.85, 0.62, 0) # Yellow/Orange
        
    p.drawString(240, height - 290, f"{report.get('db_message', 'Status Unknown')}")

    # Disclaimer & Accuracy Note (Moved to the bottom)
    p.setFont("Helvetica-Oblique", 9)
    p.setFillColorRGB(0.5, 0.5, 0.5)
    p.drawString(100, 80, "*This is an automated diagnostic report generated by MedVerify AI.")
    p.drawString(100, 70, "*Not a replacement for professional laboratory chemical analysis.")
    
    # Signature Area
    p.setStrokeColorRGB(0.8, 0.8, 0.8)
    p.line(width - 250, 100, width - 100, 100)
    p.drawString(width - 230, 85, "Digital Health Signature")

    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer